### PR TITLE
Set the upgrade path 6.10 -> 7.9

### PR DESCRIPTION
**Pull request by pirat89**
SSIA.

### CODE REVIEW

**Comment by AloisMahdal** [comment]
I've messed up scheduling of verification but one of our static tests has reported something that seems legit:  `system_TargetEUSInfo` is not present in preupg listing.  Is this expected?  (I could not find PR for that.)

**Comment by pirat89** [comment]
Discussed in person. The system_TargetEUSInfo module is downstream stuff.

**Review by bocekm — APPROVED** [review]

**Review by AloisMahdal — APPROVED** [review]
LGTM

**Comment by AloisMahdal** [comment]
preupgrade-assistant-el6toel7-0.7.9-0.202007041814Z.PR127.el6_10

`release_version`:

    6.10
    7.6

Weird.  investigating...

**Comment by pirat89** [comment]
discussed. Installed old `preupgrade-assistant-el6toel7-data`.

**Comment by AloisMahdal** [comment]
Downstream tests finished and all passed.  (Except for some minor issues irrelevant to this PR.)

**Comment by pirat89** [comment]
Thanks. merging.

**Pull request merged**
