### PR TITLE
Removing check_script and solution from module.ini files

### PR DESCRIPTION
**Pull request by jmazanek**
Removing unnecessary lines from module.ini files to reflect changes in PA related to https://github.com/upgrades-migrations/preupgrade-assistant/pull/311

### CODE REVIEW

**Comment by jmazanek** [comment]
removed also solution_type lines (consulted with mbocek) and blank lines

**Comment by jmazanek** [comment]
Copr build failed because the old compose script requires deleted lines in module.ini files. Waiting for new compose script. I will rebuild the package after

**Comment by pirat89** [comment]
@jmazanek : Where did you changed text? :-) Removing text_changed flag

**Review by AloisMahdal — DISMISSED** [review]
LGTM

**Comment by AloisMahdal** [comment]
FTR, this is also tracked downstream as https://bugzilla.redhat.com/show_bug.cgi?id=1402481

**Review by pirat89 — DISMISSED** [review]

**Comment by pirat89** [comment]
force push to reinitiate tests

**Review by AloisMahdal — DISMISSED** [review]
Still LGTM.

**Comment by pirat89** [comment]
--test--

**Review by pirat89 — APPROVED** [review]

**Pull request merged**
